# Generated by Django 4.0.4 on 2022-05-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.IntegerField(choices=[(0, 'Customer'), (1, 'Admin'), (2, 'Checker'), (3, 'Delivery')], default=0, help_text='Tipo de usuario'),
        ),
    ]
